# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNSiriWaveView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNSiriWaveView

  pod 'SCSiriWaveformView'
  pod 'PXSiriWave',:git => 'https://github.com/prscX/PXSiriWave9.git', :commit =>'bd109dd'

end
